soap_client:
    namespaces:
        'http://tempuri.org/': GoetasWebservices\Client\GeisGroupCz
        'http://schemas.datacontract.org/2004/07/GService.Manager': GoetasWebservices\Client\GeisGroupCz\DataContract\Manager
        'http://schemas.microsoft.com/2003/10/Serialization/': GoetasWebservices\Client\GeisGroupCz\Serialization
        'http://schemas.microsoft.com/2003/10/Serialization/Arrays': GoetasWebservices\Client\GeisGroupCz\Serialization\Arrays
    destinations_php:
        GoetasWebservices\Client\GeisGroupCz: src
    destinations_jms:
        GoetasWebservices\Client\GeisGroupCz: metadata
    metadata:
        'https://gclient.geis.cz/GService/GService.svc?singlewsdl': null
